In [3]:
import numpy as np

In [3]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
arr[2]

12

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
# Slicing
arr[0:4]

array([10, 11, 12, 13])

In [9]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

In [10]:
arr[6:]

array([16, 17, 18, 19])

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
# To broad the values in array
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19])

In [14]:
arr = np.arange(10,20)
slice_of_ary = arr[0:5]
slice_of_ary

array([10, 11, 12, 13, 14])

In [17]:
slice_of_ary[:] = 99
slice_of_ary

array([99, 99, 99, 99, 99])

In [18]:
# Slicing an array will not copy the array and slice it. It will directly refer the parent array
# Changing in the child changes the parent also
# It is too avoid the memory issues.If you want the copy, use the copy method
arr

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

In [19]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

In [20]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
# Now, parent didnt change
arr

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [4]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
# We can select with 2 brackets method and 1 bracket method
print(arr_2d[0][0])
print(arr_2d[0,0])
print(arr_2d[2][1])
print(arr_2d[2,1])

5
5
40
40


In [6]:
arr_2d[0]

array([ 5, 10, 15])

In [7]:
# To select the chunk of data. Use slice notation
# It will select the row upto 2, column select from 1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [8]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [9]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [10]:
another_arr = np.arange(50).reshape(5,10)
another_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [12]:
another_arr[1:3, 3:5]

array([[13, 14],
       [23, 24]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [13]:
arr2d = np.zeros((10,10))

In [16]:
arr_length = arr2d.shape[1]
for num in range(arr_length):
    arr2d[num] = num
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [18]:
arr2d[[2,4,5,2]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])