In [1]:
import numpy as np

In [3]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
arr[2]

12

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
# Slicing
arr[0:4]

array([10, 11, 12, 13])

In [9]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

In [10]:
arr[6:]

array([16, 17, 18, 19])

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [11]:
# To broad the values in array
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19])

In [14]:
arr = np.arange(10,20)
slice_of_ary = arr[0:5]
slice_of_ary

array([10, 11, 12, 13, 14])

In [17]:
slice_of_ary[:] = 99
slice_of_ary

array([99, 99, 99, 99, 99])

In [18]:
# Slicing an array will not copy the array and slice it. It will directly refer the parent array
# Changing in the child changes the parent also
# It is too avoid the memory issues.If you want the copy, use the copy method
arr

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

In [19]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

In [20]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
# Now, parent didnt change
arr

array([99, 99, 99, 99, 99, 15, 16, 17, 18, 19])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
# We can select with 2 brackets method and 1 bracket method
print(arr_2d[0][0])
print(arr_2d[0,0])
print(arr_2d[2][1])
print(arr_2d[2,1])

5
5
40
40


In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
# To select the chunk of data. Use slice notation
# It will select the row upto 2, column select from 1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [28]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])