In [3]:
import numpy as np

In [4]:
# One D Array
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
# List of List to 2-D Array
another_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(another_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Array from range
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# To get a range with step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
# Vector of Zeroes
np.zeros(3)

array([0., 0., 0.])

In [10]:
# To get 2 D zeroes, we need to pass a Tuple
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# Linspace - will return evenly spaced numbers in 1-D Vector
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Identity matrix
It is equal sized matrix mean number of rows = number of columns
<br>
Diagonal element should be 1 and everything else should be o

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

In [23]:
# It will return a uniformly distributed numbers ranging from 0 to 1
np.random.rand(5)

array([0.87396207, 0.95415664, 0.26295143, 0.56588615, 0.18545577])

In [22]:
np.random.rand(3,5)

array([[0.63662929, 0.91877099, 0.83870526, 0.43332203, 0.05948847],
       [0.94586005, 0.79250019, 0.98300426, 0.82081783, 0.98453062],
       [0.08772073, 0.21573554, 0.48360219, 0.58556435, 0.94156831]])

In [24]:
# To get random numbers from normal distribution
np.random.randn(5)

array([-0.42743181,  0.4010317 ,  0.99890166,  1.09745408, -0.39775299])

In [27]:
np.random.randn(5,3)

array([[-0.25696345,  0.39888988, -0.22663806],
       [ 0.33617988,  0.86675195, -0.07901908],
       [-0.1588017 ,  1.6536788 ,  0.50769381],
       [-1.30489471,  1.8272779 , -0.68037288],
       [ 0.34921971,  0.68947399, -1.46063286]])

In [28]:
# Random integers
# Lowest number is inclusive and highest number is exclusive
np.random.randint(50)

9

In [30]:
# It will return a 1-D array of 10 random integers ranging from 0 to 99
np.random.randint(0,100, 10)

array([50, 26, 27, 74, 58, 48, 68, 43, 14, 90])

## from numpy.random import randint

In [31]:
# Instead of calling np.random.randint, we can do below one
from numpy.random import randint
randint(100)

35

In [32]:
randint(0,10,5)

array([4, 1, 4, 2, 0])