In [3]:
import numpy as np

In [4]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Array of Boolean values
bool_arr = arr > 5
bool_arr

array([False, False, False, False,  True,  True,  True,  True])

In [8]:
# If I pass the bool_arr to any arr, it will find the statement which falls under True
arr[bool_arr]

array([6, 7, 8, 9])

In [9]:
arr[arr>5]

array([6, 7, 8, 9])

In [10]:
arr[arr<4]

array([2, 3])