In [1]:
import numpy as np

In [2]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [10]:
# It will return the shape
arr.shape

(25,)

In [14]:
# To reshape an existing array
arr = arr.reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
arr.shape

(5, 5)

In [17]:
# It will return the data type
arr.dtype

dtype('int32')

In [5]:
# If we don't have enough elements or having extra elements, it will throw an exception
# You can only fill with what you have
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [6]:
rand_arr = np.random.randint(0,50,10)
print(rand_arr)

[44 34 45 43 33  9 11 34 35  4]


In [7]:
print(rand_arr.max())
print(rand_arr.min())

45
4


In [8]:
# To find the index location of max and min value
print(rand_arr.argmax())
print(rand_arr.argmin())

2
9
